---
title: "tropic-thunder-cleaning"
author: "Annie Adams"
format: html
editor: visual
---

### Import libraries

```{r}
library(here)
library(tidyverse)
library(dplyr)
library(janitor)
library(lubridate)

library(plotly)
```

### Import data

LUQ LTER method detection limits

Quebrada one-Bisley (Q1) Chemistry Data

Quebrada two-Bisley (Q2) Chemistry Data

Quebrada three-Bisley (Q3) Chemistry Data

```{r}
PRM <- read_csv(here("raw-data","RioMameyesPuenteRoto.csv"))
Q1 <-  read_csv(here("raw-data", "QuebradaCuenca1-Bisley.csv"))
Q2 <-  read_csv(here("raw-data", "QuebradaCuenca2-Bisley.csv"))
Q3 <-  read_csv(here("raw-data", "QuebradaCuenca3-Bisley.csv"))

```

### Clea data

```{r}
PRM_clean <- PRM %>%
  clean_names() %>% 
  mutate(clean_date = lubridate::ymd(sample_date)) %>% 
  mutate(clean_year = lubridate::year(sample_date)) %>% 
  filter(clean_year ==1989 |clean_year== 1990 |
         clean_year == 1991| clean_year == 1992|
         clean_year == 1993 | clean_year == 1994) %>% 
         select(clean_date, no3_n, k, sample_id)
  

Q1_clean <- Q1 %>%
  clean_names() %>% 
  mutate(clean_date = lubridate::ymd(sample_date)) %>% 
  mutate(clean_year = lubridate::year(sample_date)) %>% 
  filter(clean_year ==1989 |clean_year== 1990 |
         clean_year == 1991| clean_year == 1992|
         clean_year == 1993 | clean_year == 1994) %>% 
         select(clean_date, no3_n, k, sample_id) 

Q2_clean <- Q2 %>%
  clean_names() %>% 
  mutate(clean_date = lubridate::ymd(sample_date)) %>% 
  mutate(clean_year = lubridate::year(sample_date)) %>% 
  filter(clean_year ==1989 |clean_year== 1990 |
         clean_year == 1991| clean_year == 1992|
         clean_year == 1993 | clean_year == 1994) %>% 
         select(clean_date, no3_n, k, sample_id)

Q3_clean <- Q3 %>% clean_names() %>% 
  mutate(clean_date = lubridate::ymd(sample_date)) %>% 
  mutate(clean_year = lubridate::year(sample_date)) %>% 
  filter(clean_year ==1989 |clean_year== 1990 |
         clean_year == 1991| clean_year == 1992|
         clean_year == 1993 | clean_year == 1994)%>% 
  select(clean_date, no3_n, k, sample_id)
```

### Combine rows into one table

```{r}
total_data1<- bind_rows(PRM_clean,Q1_clean)
total_data2<- bind_rows(total_data1, Q2_clean)
total_data <- bind_rows(total_data2, Q3_clean)
```

### Generate k plot

```{r}
k_plot <- ggplot(data = total_data , aes(x = clean_date, y = k))+
  geom_line(aes(color = sample_id), show.legend = FALSE) +
  labs(x = "Year",
       y = "Potassium")
 
 k_plot
```

### Generate n plot

```{r}
 n_plot <- ggplot(data = total_data , aes(x = clean_date, y = no3_n))+
  geom_line(aes(color = sample_id), show.legend = FALSE)+
  labs(y = "Nitrate")+
  theme(axis.title.x=element_blank(),
        axis.text.x = element_blank())
  
 
 n_plot
```

### Combine k and n plots

```{r}
final_plot <- subplot(style(n_plot, showlegend = F),
                      k_plot, nrows = 2, titleY = TRUE, titleX = TRUE)  %>% 
  layout(title = "Water Stream Chemistry - Luqillo Mountains",
         legend=list(title=list(text='<b>  Site </b>')))

final_plot
```
