---
title: "Exploratory Analysis"
format: html
editor: visual
---

## Targets Code

```{r}
library(targets)
```

```{r}
use_targets()
```

```{r}
tar_target(PRM, "raw-data/RioMameyesPuenteRoto.csv", format = "file")
# Reading in PRM
tar_target(Q1, "raw-data/QuebradaCuenca1-Bisley.csv", format = "file")
# Reading in Q1
tar_target(Q2, "raw-data/QuebradaCuenca2-Bisley.csv", format = "file")
# Reading in Q2
tar_target(Q3, "raw-data/QuebradaCuenca3-Bisley.csv", format = "file")
# Reading in Q3

# CAUTION BEFORE RUNNING, CHECK ABOUT THE NAMING OF NEW DATA
# I want to save this data in the read in file that is then cleaned

# Do I need to write the cleaning portion here

tar_target(PRM_data, get_data(PRM))
# Grabbing PRM data
tar_target(Q1_data, get_data(Q1))
# Grabbing Q1 data
tar_target(Q2_data, get_data(Q2))
# Grabbing Q2 data
tar_target(Q3_data, get_data(Q3))
# Grabbing Q3 data

# Cleaning data sets
# ? How do I demonstrate this code properly in target

tar_target(PRM_clean, site_df(PRM_data))
           
           
           
 
```
