---
title: "diatom-vis"
author: soapy soap
format: html
editor: visual
---

## Libraries

```{r}
library(here)
library(tidyverse)
library(janitor)
library(dplyr)
library(lubridate)
```

## Read in Data

```{r}
# read in diatom data
Q3_diatom_raw <- read_csv(here("diatom-raw-data", "Mameyesdiatomdata.csv")) %>% 
  janitor::clean_names()

# read in chemistry data to compare
Q3_ph <-  read_csv(here("raw-data", "QuebradaCuenca3-Bisley.csv")) %>% 
  janitor::clean_names()
```

## Clean Data

```{r}
# clean Q3 data
Q3_ph_clean <- Q3_ph %>% clean_names() %>% 
  mutate(clean_date = lubridate::ymd(sample_date)) %>% 
  select(clean_date, p_h, sample_id)

# filter diatom data to only Q3 site
Q3_d_clean <- Q3_diatom_raw %>% 
  filter(site == "BQ3")
```

## Combining Data

```{r}
convert_to_ISO <- function(date_string) {
  parsed_date <- mdy(date_string)
  iso_date <- as_date(parsed_date)
  return(iso_date)
}

Q3_d_clean <- Q3_d_clean %>% 
  mutate(clean_date = convert_to_ISO(date))
```

```{r}
Q3_ph_d_join <- cross_join(Q3_ph_clean, Q3_d_clean)

View(Q3_ph_d_join)
# it would be interesting to investigate the variations in side 1:3 percent_live as a variable of pH
# potential option to explore reasoning for this for the presentation
```

### pH vs Percent alive

```{r}
agg_data <- Q3_ph_d_join %>%
  group_by(p_h, percent_live) %>%
  summarize(count = n(), .groups = "drop")
```

```{r}
x <- colnames()
ggplot(agg_data, aes(x = as.factor(p_h))) +
  geom_tile(aes(fill = ..count..), stat = "count") +
  scale_fill_gradient(low = "white", high = "blue") +
  labs(x = "p_h", fill = "Frequency") +
  theme_minimal()
```

## Selecting columns

```{r}
# Creating column vector to call
Q3_cols <- c("p_h", "side", "percent_live", "clean_date")

# Slicing df
# ATTENTION THIS DATA FRAME CONTAINS DOUBLES AND CHR 
# NEEDS TO BE CONVERTED TO NUMERIC TO PLOT
Q3_plot_df <- Q3_ph_d_join %>% 
  select(p_h, side, percent_live, clean_date) %>%
 
  
  # mutate(across(is.double(), as.numeric(), na.rm = TRUE)) %>% 
  #mutate(across(is.character(), as.numeric(), na.rm = TRUE))

#mutate(across(p_h:clean_date, as.numeric(), na.rm = TRUE))

 # mutate(across(Q3_cols, is.numeric)
  
# %>%  filter(!is.na(percent_live))

View(Q3_plot_df)
```

## Data Viz

```{r}
Q3_ph_plot <- ggplot(data = Q3_plot_df, aes(x = clean_date, y = p_h)) +
  geom_jitter(aes(color = side))
<<<<<<< HEAD
 # labs(x = "Year", y = "pH")
View(Q3_plot)
=======
 # labs(x = "pH", y = "Percent of Living Diatom")
View(Q3_ph_plot)
>>>>>>> 14903f35db4c50caffdbbcd052d5625480df8c2f
```

https://towardsdatascience.com/explore-two-variables-using-r-68ece9cbcd81

```{r}
Q3_pl_plot <- ggplot(data = Q3_plot_df, aes(x = clean_date, y = p_h)) +
  geom_jitter(aes(color = side))
 # labs(y = "Percent of Living Diatom") + theme(xaxis = FALSE) // line needs to be fixed
View(Q3_plot)
```
